<?php

/*@
 *@Author: Shaun Childerley
 *@Email: shaun@creativemiles.co.uk
 *@Name: Save Mari
 *@Start: 15th December 2016
*/
if(!defined('IN_ROOT')) { die('You can not access this file directly!'); }
?>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Our Services</h1>
      
      <p>1. Buy&amp; Sell Online</p>
<p><br />Our online buying and selling platform allows you to make direct purchases, this will save you<br />Time rather than physically walking into a store and buying goods or services.</p>
<p>Below we have listed a few advantages of online buying and selling;<br />&bull; Making savings in set-up and operational costs. You do not need to rent a high priced street premise, pay shop assistants or answer a lot of pre-sales queries.<br />&bull; Reducing order processing costs - customer orders can automatically come straight into your<br /> Database from the website.<br />&bull; Reaching a global audience, thereby increasing sales opportunities.<br />&bull; Competing with larger businesses by being able to open 24 hours a day, seven days a week.<br />&bull; Being able to receive payment more quickly from online transactions.<br />&bull; Attracting customers who would not normally have investigated your type of high street outlet.<br />&bull; Improving your offerings using the data gathered by tracking customer purchases.<br />&bull; Using your online shop as a catalogue for existing customers.</p>
<p>2. Online stores<br />To have an online store on savemari.com will take you only 10 -20 minutes, we have developed our website in a way that will enable you to quickly fill in your details thereby saving you time. Basically, to have an online store is creating your website on our savemari site. You will be taking your whole physical business or store, and placing it online at savemari.com, thereby taking your business to another level. You will be able to share your store with anyone in the world, on Facebook, Whats-app,Twitter, LinkedIn and anywhere online, you can even add your store address on your business card. Imagine if someone wants to refer your business to someone who is in the UK, how will they do that if you are not online? Once you have an online store with us. We will take you to new territories around the world just by a click of a button. You will be able to reach out to Zimbabweans scattered across Glob such as the UK, South Africa, Canada, USA, Australia, Dubai, China Singapore and many more other countries. Let&rsquo;s not forget that we have over 5 million Zimbabweans who are leaving abroad, with an estimate savings of over $800 million dollars in their bank accounts. These people are keen to do business with local businesses here in Zimbabwe. In simple terms, your store and products being seen by customers from all over the world will increase your customer base by over 50%.</p>
<p>The other benefit of having an online store as compared to just a normal advert is that, customers can find more details about your business, hence boosting your customers' confidence. Your customers will be able to give you ratting, write comments, and recommendations on your store. This alone will increase your revenue, and it will give you a chance to make improvements thereby coming out with a much-improved product or service. You will get many links from the diaspora, customers will share your business, encourage more diaspora people to trade with you. Your business will grow beyond your imagination.<br />To subscribe please contact our sales team at adverts@savemari.com</p>
<p>3. Click and Collect<br />Click and collect is all about customers making a purchase online on our website using our guaranteed unique system. Customers can buy with ease and go collect their purchased goods in store or from an agreed location with the seller. It&rsquo;s the only one of a kind, designed and patterned by SaveMari .This system will grantee you as a customer, that you will get what you paid for as advertised on the SaveMari store(s) or your money back. When making a purchase using our Click &amp; Collect system, customer(s)/buyer(s) are issued a PIN number that locks their money until their goods/services are delivered. When the buyer/ customers&rsquo; money leaves their account, it will go into a secure escrow account, where no seller/ store owner has access to. When the customer or buyer is happy with your goods and services, then you will exchange your goods/ services with the PIN. The seller, or store owner will then activate the PIN so that they can get their money from the secure escrow account.<br />We&rsquo;ve developed this unique digital platform allowing both buyers &amp; sellers to offer a revolutionary shopping experience trading online with ease and in a transparent manner. Our click and Collect system is what online shoppers have been waiting for!</p>
<p><br />Benefits for customers<br />Customers who use our Click &amp; Collect get to control their money until their goods and services are delivered. You no longer have to consider or think about missing any of your paid goods online. You will be no more a victims of online scams. The days of sleepiness nights after buying anything online will be over. You as a customer, will be in control of your money. With our Click &amp; Collect, you are guaranteed of what you have paid for or you get your money back. With this in mind, you are rest assured to be buying from genuine sellers using our Click and Collect. Our unique system will change the way business is done online in Africa, only genuine and reputable business is what SaveMari is all about. As a customer, you will have the power to leave feedback, sellers ratting, and comments. <br />Contact us for more information and details about our Click &amp; Collect.</p>
<p>4. Sponsored &amp; Featured Adverts<br />Featured ads are a fantastic way of differentiating your ad from the rest in the specific subcategory you&rsquo;re placing it in. Featured ads also remain above normal ads, which means users will view Featured ads first. The goal behind it is to give more exposure to your ad and generate more leads that results in a faster sale. Our numbers indicate that on average featured ads get 35 times more leads and 18 times more<br />Views on the site over normal ads. These are adverts that are carefully placed on more prime areas of our websites. The featured adverts are the adverts that are seen as soon as you log to our site, just below are featured stores .They are on top of every page. With our featured adverts, there is an 80% chance of been seen by someone browsing and searching for a specific item. When you pay for your advert. Customers will mostly trust paid Featured adverts that Free adverts online.</p>
<p>5. Sponsored adverts <br />These are the adverts that come below every single page on our site. They will be running across below every single advert. The system, will select carefully all sponsored advert for that specific advert category. If someone is looking at an advert, the sponsored advert will run below that advert as alternative to what the customer is looking for. Hence giving it a greater 60% chance for someone who will be browsing an adverts to see similar advert below. This will give the customer a better chance to compare thereby increasing the chance of your sponsored advert been seen too.</p>
<p>6. Banner adverts<br />Banner ads are image-based rather than text-based and are a popular form of website advertising. The purpose of banner advertising is to promote your brand by advertising your services or goods on the front page of our website, the front welcome page is where every viewer of the website starts browsing so they will definitely see your banner first. It could be anything that attracts your targeted customers. Colourful picture with less text are ideal for banners. There is a higher chance that they would look at it first, then click to see more of your information. The system will then divert them to your own website or page of your choice. This is one of the most popular ways of diverting our high volume traffic to your own website of product that you will be running a campaign for.</p>
<p>Advantage of banner advert<br />Building Brand Recognition while banner advertising ideally generates immediate sales, its role in building brand recognition makes the ads a useful marketing tool even when Web surfers don&rsquo;t click the banner. In the book &amp; Integrated Marketing Communications banner ads are effective in progressing a potential customer from unawareness of your product or service to awareness, in which your brand is the first that comes to a buyer in mind.<br />If you wish to place a banner SaveMari.com please contact our sales team on adverts@savemari.com</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
      

    </div>
  </div>
</div>
